-- AlterTable
ALTER TABLE `Soldier` ADD COLUMN `accidentSequelae` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `accidentSequelaeDetails` TEXT NULL,
    ADD COLUMN `alcoholUse` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `arrestDetails` TEXT NULL,
    ADD COLUMN `childrenCount` INTEGER NULL,
    ADD COLUMN `familyIncome` DECIMAL(10, 2) NULL,
    ADD COLUMN `hadSurgeries` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasBeenArrested` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasMilitaryRelative` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasSTDs` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasSeizuresFainting` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasSiblings` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `helpsFamily` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `helpsFamilyAmount` DECIMAL(10, 2) NULL,
    ADD COLUMN `householdCount` INTEGER NULL,
    ADD COLUMN `irritabilityAnxietyEtc` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `irritabilityAnxietyEtcDetails` TEXT NULL,
    ADD COLUMN `livedAway` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `livedAwayWhere` TEXT NULL,
    ADD COLUMN `livesWithParents` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `livesWithWhom` TEXT NULL,
    ADD COLUMN `lostCloseFamily` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `lostWhoCause` TEXT NULL,
    ADD COLUMN `mentalSymptoms` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `mentalSymptomsDetails` TEXT NULL,
    ADD COLUMN `militaryRelativeDetails` TEXT NULL,
    ADD COLUMN `policeProblems` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `policeProblemsDetails` TEXT NULL,
    ADD COLUMN `relationshipFather` TEXT NULL,
    ADD COLUMN `relationshipMother` TEXT NULL,
    ADD COLUMN `relationshipSiblings` TEXT NULL,
    ADD COLUMN `siblingsCount` INTEGER NULL,
    ADD COLUMN `smoker` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `stdDetails` TEXT NULL,
    ADD COLUMN `suddenFear` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `surgeriesDetails` TEXT NULL,
    ADD COLUMN `tattoos` TEXT NULL,
    ADD COLUMN `volunteeredToServe` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workDetails` TEXT NULL,
    ADD COLUMN `workSalary` DECIMAL(10, 2) NULL,
    ADD COLUMN `workSignedCard` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workedBeforeEB` BOOLEAN NOT NULL DEFAULT false;
